using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using Vidley.Dtos;
using Vidley.Models;

namespace Vidley.Controllers.Api

{
    public class CustomersController : ApiController
    {
        private ApplicationDbContext _context;

        public CustomersController()
        {
                _context = new ApplicationDbContext();
        }

        // Get /api/customers/
        public IEnumerable<CustomerDto> GetCustmers()
        {
            return _context.Customers.ToList().Select(Mapper.Map <Customer, CustomerDto>);
        }

        //Get /api/customerDto/1
        // similar to details
        //
        //public Customer GetCustomer(int Id) -- THIS WAS BEFORE MAPPING
        public IHttpActionResult GetCustomer(int Id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == Id);
            if (customer == null)
            {
                return NotFound();
            }
            return Ok( Mapper.Map<Customer,CustomerDto>(customer));
            //return customerDto;
        }

        //Post /api/customers/
        // similar to Save
        [HttpPost]
        //public Customer PostCustomer(Customer customerDto)
        public IHttpActionResult CreateCustomer(CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();            
            var customer = Mapper.Map<CustomerDto, Customer>(customerDto);
            _context.Customers.Add(customer);
            _context.SaveChanges();
            // this time the Id property will be set generated by the database object
            //return customerDto;

            customerDto.Id = customer.Id;
            return Created(new Uri(Request.RequestUri + "/" + customer.Id), customerDto );
        }

        // PUT / api/customers/1
        // simliar to edit
        [HttpPut]
        //        public void UpdateCustomer(int id, Customer customerDto)

        public IHttpActionResult UpdateCustomer(int id, CustomerDto customerDto)
        {

            if (!ModelState.IsValid)
                return BadRequest();
            var customerIndb = _context.Customers.SingleOrDefault(c => c.Id == id);


            if (customerIndb == null)
            {
                return NotFound();
            }
            Mapper.Map(customerDto, customerIndb);
  
            _context.SaveChanges();
            return Ok();

        }
        //Delete /api/customers/1
        [HttpDelete]
        public IHttpActionResult DeleteCustomer(int id)
        {
            var customerIndb = _context.Customers.SingleOrDefault(c => c.Id == id);
            if (customerIndb == null)
            {
                return NotFound();
            }
            _context.Customers.Remove(customerIndb);
            _context.SaveChanges();
            return Ok();
        }
    }
}
